name: tests

on:
  push:
    branches: ['*']

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies (for simpleaudio)
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies and run tests
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m doctest -v docchat.py
